### ISSUE TITLE
Xenobio hallway is a mess

### ISSUE THREAD

**Issue by Eimras** [Dropshotz/PFStation#37]
#### Brief description of the bug
![image](https://user-images.githubusercontent.com/9496888/103144605-667a6e00-46fa-11eb-9862-1ef3d0fb4666.png)

#### What you expected to happen
![image](https://user-images.githubusercontent.com/9496888/103144613-7bef9800-46fa-11eb-891a-34920c3bbc82.png)

#### What actually happened
![image](https://user-images.githubusercontent.com/9496888/103144605-667a6e00-46fa-11eb-9862-1ef3d0fb4666.png)

#### Steps to reproduce
- (Step 1)
- log in
- (Step 2)
- look at Xenobiology

#### Code Revision
- GLOB.revdata.revision(lol)

**Comment by Dropshotz** [comment]
![image](https://user-images.githubusercontent.com/22395438/103149104-1d183600-476f-11eb-9072-1c8865b124f8.png)
Scrubber should be one up
